name: PvpToggle
main: me.xgh69.pvptoggle.main.PvpToggle
version: 1.9
author: xgh69
commands:
  pvp:
    description: Manage your pvp settings
  pvpadmin:
    description: PvpToggle admin command
permissions:
  pvptoggle.admin:
    default: op
    description: Permission for admins.
