name: PvpToggle
main: me.xgh69.pvptoggle.PvpToggle
version: 1.3
author: xgh69
softdepend: [WorldEdit, WorldGuard]
commands:
  pvp:
    description: Manage your pvp settings
  pvpadmin:
    description: PvpToggle admin command
permissions:
  pvptoggle.admin:
    default: op
    description: Permission for admins.
